class ACTION_TYPE {
  static ISFIRST = 'CHANGE_STATUS_ISFIRSTOPEN';
  static UPDATE_USER = 'UPDATE_USER';
  static UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
  static UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
  static UPDATE_CURRENTSCHEDULE = 'UPDATE_CURRENT_SCHEDULE';
  static UPDATE_USERROLE = 'UPDATE_USERROLE';
  static UPDATE_USERATTENDEXPIRED = 'UPDATE_USERATTENDEXPIRED';
  static CLEAR_DATA = 'CLEAR_DATA';
}

export default ACTION_TYPE;
